alphagov/pay-smoke-tests

README.md
There is a 21-character limit on Canary resource names, so let's add a handy guide to the README.
The worldpay 3ds2 exemption tests are *juuuust* squeezed into 21 characters!
=> PP-7887: Abbreviations for Canary resource names

helpers/smokeTestHelpers.js
Our Canaries are intermittently timing out on the `page.waitForNavigation` commands. Increase the timeout from 30s to 60s for now, and use `waitUntil: domcontentloaded` to hopefully speed this up (i.e. don't wait for images/frames to be loaded). We use this pattern already in the `page.goto` commands ([example here](https://github.com/alphagov/pay-smoke-tests/blob/main/helpers/smokeTestHelpers.js#L122)).
See https://pptr.dev/#?product=Puppeteer&version=v8.0.0&show=api-pagewaitfornavigationoptions for details on the options.
=> PP-7887: Increase timeout for page.waitForNavigation

README.md
Updates the README with info on the Github Actions release process.
Merging this PR should also build a release, so we can test our pipeline 😸
=> PP-7887: Update README with release information

helpers/smokeTestHelpers.js
This step in the helper function was causing the smoke tests that use it to intermittently timeout.
We've tested removing this line on the following canaries and they've passed (where they previously were failing more often than not):
- `card_wpay_3ds_test`
- `card_sandbox_test`
- `card_wpay_test`
=> PP-7887: Remove waitForNavigation step from enterCardDetailsAndSubmit helper

.github/workflows/pull_request.yaml, .github/workflows/release.yaml
This changes the cache keys used by the caching steps between multiple Jobs of a Github Actions workflow. By making these changes, we should reduce the chance that stale assets could be reused for a subsequent run.
N.B. The changes to the PR pipeline are likely not going to take effect until this PR is merged into main.
=> [PP-7873] Potential Actions Cache Key Fix

.github/workflows/pull_request.yaml, .github/workflows/release.yaml
So it looks like the previous environment variable didn't exist in the context of our caching action, so I have switched all the `GITHUB_SHA` environment variables to use the `github.sha` context variable instead.
Again, the change from this will likely not be visible until merged into main.
=> [PP-7873] Another cache key fix using the `github` context.

run-local/index.js, use-payment-link-for-sandbox/index.js
The `waitForNavigation()` function returns a promise which resolves the
next time the page navigates to a new URL or reloads. As per the
puppeteer docs the promise should be obtained before the action to
change pages or reload, and then `await` for the promise to revolve to
signal that the action has completed.
Previously the test was obtaining and waiting for the promise to resolve
after it had performed the page action. This meant on ocassion the page
had already completed the navigation before `waitForNavigation()` was
invoked and the promise obtained, and the test would timeout waiting for
the navigation to complete after it had already done so.
Link to the puppeteer docs:
https://github.com/puppeteer/puppeteer/blob/v1.7.0/docs/api.md#pagewaitfornavigationoptions
[As per the puppeteer …
=> PP-7887 Fix flakiness of payment link test

notifications-sandbox/index.js, run-local/index.js
Simply makes a POST request to the sandbox notifications endpoint and
expects to receive a HTTP 200 response code. Updated the run-local
script to include this test.
See it running locally (secrets added for test env only so far)
```
gds5062-2:pay-smoke-tests danworth$ aws-vault exec deploy -- node run-local/index.js --test notifications-sandbox --env test
Running notifications-sandbox
Sending POST request to notifications-test-12.test.pymnt.uk/v1/api/notifications/sandbox
Notifications responded with 200 OK
```
Running the test with an invalid API token yeilds
```
gds5062-2:pay-smoke-tests danworth$ aws-vault exec deploy -- node run-local/index.js --test notifications-sandbox --env test
Running notifications-sandbox
Sending POST request to …
```
=> PP-8387 Add notifications smoke test

.github/workflows/build.yaml
Fix copy and paste error. Replace with a simple means of checking the
branch name using basic Github Actions syntax.
Whops, copied from another workflow file in pay-dockerfiles but this file does not have the step it relies upon. Github docs showing example: https://docs.github.com/en/actions/reference/context-and-expression-syntax-for-github-actions#determining-when-to-use-contexts
=> PP-8387 Correct the if condition for creating a release

make-card-payment-stripe-with-3ds2/index.js, stubs/syntheticsStub/index.js
Update the Stripe 3DS2 tests to correctly complete the 3DS challenge
Iframe.
Change the puppeteer stubs which are used for local running so they run
in headed mode which is more useful when running locally.
Stripe 3DS seems a bit more complicated than Worldpay because its an iframe in an iframe. I've run these tests for test, staging and production locally and they pass.
The following change to the puppeteer stub is necessary when running in headed mode in order to get the iframes.
```
args: [
'--disable-features=IsolateOrigins,site-per-process'
],
```
```
gds5062-2:pay-smoke-tests danworth$ aws-vault exec deploy -- node run-local/index.js --env production --test make-card-payment-stripe-with-3ds2
Running make-card-payment-stripe-with-3ds2
Going to create a payment to stripe
Going to get …
```
=> PP-8512 Fix Stripe 3ds2 tests

README.md, run-local/index.js, stubs/syntheticsStub/index.js
Also add a help text to the command.
```
gds5062-2:pay-smoke-tests danworth$ aws-vault exec deploy -- node run-local/index.js --env production --test make-card-payment-stripe-with-3ds2 --headless
```
and 
```
gds5062-2:pay-smoke-tests danworth$ aws-vault exec deploy -- node run-local/index.js --env production --test make-card-payment-stripe-with-3ds2
```
help text/usage provided
```
gds5062-2:pay-smoke-tests danworth$ aws-vault exec deploy -- node run-local/index.js
Options:
--env must be one of: test,staging,production
--test must be one of:
make-card-payment-sandbox-without-3ds,make-card-payment-smartpay-without-3ds,make-card-payment-stripe-with-3ds2,make-card-payment-stripe-without-3ds,make-card-payment-worldpay-with-3ds,make-card-payment-worldpay-with-3ds2,make-card-payment-worldpay-wi …
```
=> PP-8512 Add the option to run the tests locally in headless mode.

notifications-sandbox/index.js
This update to the Sandbox Notification Smoke Test sends a non-empty body along with our POST request to `/v1/api/notifications/sandbox` so as not to get trapped by NAXSI Rule 16, "Empty POST".
=> [PP-8910] Populate POST to Notifications Sandbox

notifications-sandbox/index.js
As it was it errors with:
```
Running notifications-sandbox
Sending POST request to
notifications-test-12.test.pymnt.uk/v1/api/notifications/sandbox
test failed: https.request(...).write(...).end is not a function
```
This fixes it so it runs correctly:
```
Sending POST request to
notifications-test-12.test.pymnt.uk/v1/api/notifications/sandbox
Notifications responded with 200 OK
```
Run the test locally (against the env of your choice and using the same secrets from deploy account) with the following (instructions in [README](https://github.com/alphagov/pay-smoke-tests/blob/main/README.md#test-harness)). This was run against test-12 with release 51 of notifications (which has the updated naxsi rules).
```
gds5062-2:run-local danworth$ aws-vault exec deploy -- node index.js --env test …
```
=> PP-8910 Fix Notifications Sandbox test

.github/workflows/build.yaml
Following changes to alphagov default settings. The GHA workflow needs `contents:write` permissions to create a release.
See https://github.com/alphagov/pay-nginx-forward-proxy/pull/22 for the equivalent change in nginx-forward-proxy.
=> PP-9216: Fix GHA workflow permissions

.github/workflows/build.yaml
Our GHA policy states we should pin all actions to a commit SHA, regardless of source.
- cache 2.1.7
- checkout 2.4.0
- github-script 3.1.1
- setup-node 3.0.0
- upload-artifact 2.3.1
I've already added the SHA pins in the settings.
=> PP-9308: Pin workflow actions to a SHA

.github/workflows/build.yaml
Involves breaking changes to the github context object (see [changelog](https://github.com/actions/github-script/releases)).
This looks to have worked for v6 as well as v5, so I'll squash the commits on merge.
The SHA pin has been added to the repo settings.
=> PP-9308: Try github-script v6

.github/workflows/post-merge.yml, .github/workflows/run-tests.yml
- Splits the workflow file into `run-tests` and `post-merge`. There aren't actually any unit tests here, only linting (but hopefully we'll add some in the future). I've kept the behaviour of each the same as before: lint/build pre-merge, lint/build/release post-merge.
- Adds the concurrency group to limit post-merge runs to one-at-a-time
=> PP-9376 Split release workflow and add post-merge concurrency group

.github/workflows/post-merge.yml
See ADR https://github.com/alphagov/pay-architecture/pull/49/files
=> BAU: Exclude Github Actions/Dependabot from post-merge worklow

helpers/smokeTestHelpers.js, package.json, use-payment-link-for-sandbox/index.js
Update the payment link test to work with the new payment link journey.
The new journey adds in a start page and a confirm page to the journey.
Going to leave the payment link URL as it is, and just update the
existing payment links on the smoke test accounts to use the new journey
once this has deployed.
=> PP-9937 Update payment link test

.github/workflows/run-tests.yml, .pre-commit-config.yaml, .secrets.baseline
**WHAT**
•	added a new github action to run detect-secrets
•	updated the pre-commit config to update the detect-secrets hook to version 1.4
•	rebaselined the repository's secrets baseline
Based on [alphagov/pay-webhooks#510](https://github.com/alphagov/pay-webhooks/pull/510)
**For reviewers**
•	ensure your local version of detect-secrets matches the latest version in use on this branch
•	run detect-secrets scan and ensure output matches the latest .secrets.baseline, the only change should be the generated timestamp
=> PP-10116: Add detect-secrets workflow and update version

helpers/smokeTestHelpers.js, package.json
Add backoff retries for getting webhook object from s3.
Change environment and account variable/param names so they are accurate
Maximum wait time is 20 seconds total.
```
npm install
aws-vault exec deploy -- node run-local/index.js --env test --test make-card-payment-stripe-without-3ds --webhooks
```
To test the retries change the code to pass a nonsense paymentId to the withBackoffRetries function https://github.com/alphagov/pay-smoke-tests/compare/bau-backoff-wait-for-webhook-received?expand=1#diff-dac4b7d71b02e1658fad969d77e64147110860158db9c35fcf8a58c64459a3ffR280
you'll see
```
Payment status is success
Waiting 1000ms
Looking for key: webhooks/test-12/foo
Webhook payload not received yet after 1 seconds
Waiting 2000ms
Looking for key: webhooks/test-12/foo
Webhook payload not …
```
=> Bau backoff wait for webhook received

.github/workflows/post-merge.yml
Located and replaced all usages of set-output commands in our workflows.
=> PP-10675: replaced usage of set-output in post-merge.yml

.github/workflows/post-merge.yml
Following an ordinary dependabot merge, the post-merge release workflow failed as the version number was not being correctly set to the GITHUB_OUTPUT env. I think this was because the statement was missing an `echo` but I'm not sure - let's try it out.
=> BAU: Try a fix for post-merge release version output

.github/workflows/post-merge.yml
[The previous fix attempt](https://github.com/alphagov/pay-smoke-tests/pull/162) didn't work - see https://github.com/alphagov/pay-smoke-tests/actions/runs/4498791156/jobs/7915870308 for an example failure run. 
This fix adds quoting to the `echo` command (that's being run via a Node script). Also removes the unnecessary env var in the create-zip step (to rule out that causing the error).
=> BAU: Fix for NEXTVERSION output variable

.github/workflows/post-merge.yml
For some reason the current Get Next Version Number workflow step is not registering the NEXTVERSION env var in GITHUB_OUTPUT. [See the latest failed run](https://github.com/alphagov/pay-smoke-tests/actions/runs/4666575445/jobs/8261331491):
```
Current Release Name: v82
Next Release Version: v83
echo "NEXTVERSION=v83" >> $GITHUB_OUTPUT
ZIPFILENAME="pay-smoke-tests-"
```
Instead, let's try using a similar parse method to that which we use for [carbon-relay release tagging](https://github.com/alphagov/pay-dockerfiles/blob/main/.github/workflows/carbon-relay-post-merge.yml#L56) - `git describe` and a bit of string manipulation.
=> BAU: Parse latest release number with bash instead of node

.github/workflows/post-merge.yml
Otherwise the 'git describe' command in the `Parse Version Number` step will not be able to find the git repo.
See previous run: https://github.com/alphagov/pay-smoke-tests/actions/runs/4734433221/jobs/8403373932
=> BAU: Include actions/checkout in post-merge workflow

README.md, helpers/agreement-test-helpers.js, helpers/smoke-test-helpers.js, make-recurring-card-payment-stripe/index.js, run-local/index.js, webpack.config.js
- Added a new smoke test for Stripe recurring card payments which
- creates agreement
- sets up the agreement by taking a payment
- takes a recurring payment
- Test works for all environments
**Test**
<details>
<summary>aws-vault exec deploy -- node run-local/index.js --test make-recurring-card-payment-stripe --env test --headless</summary>
```
Running make-recurring-card-payment-stripe
Webhooks steps are disabled, pass --webhooks to enable them
Creating agreement for [stripe]
Created agreement [goui3gd865e23tq9nhce4njb6i]
Setting up a payment for [stripe] and agreement [goui3gd865e23tq9nhce4njb6i]
Created payment [tr3cahhifen454roqvk7fhu1tv] for agreement [goui3gd865e23tq9nhce4njb6i]
Going to get page https://card.pymnt.uk/secure/9a2144a4-18d6-4669-a4c1-58e423b0997b
Finished setting up …
```
=> PP-10496 Smoke test for Stripe recurring card payment

README.md, helpers/recurring-card-payment-test-helpers.js, make-recurring-card-payment-sandbox/index.js, run-local/index.js
- Added a new smoke test for Stripe recurring card payment which - creates an agreement - sets up the agreement by taking a payment - takes a recurring payment for the agreement
- Added recurring card payment test helpers so these can be used by Stripe/Worldpay smoke tests for recurring payments
- Works for all environments:
**Test**
```
➜   aws-vault exec deploy -- node run-local/index.js --test make-recurring-card-payment-sandbox --env test --headless
Running make-recurring-card-payment-sandbox
Webhooks steps are disabled, pass --webhooks to enable them
Creating agreement for [sandbox]
Created agreement [200hu00lcvg721cn82ji6l7u3q]
Setting up a payment for [sandbox] and agreement [200hu00lcvg721cn82ji6l7u3q]
Created payment [sob2raouqm2vsv2r15bjl0o77v] for agreement …
```
=> PP-11029 Smoke test for Sandbox recurring card payment

helpers/smoke-test-helpers.js, make-recurring-card-payment-stripe/index.js, run-local/index.js
- Refactored Stripe recurring card smoke test to use helpers
- Also updated return_url for payments as the existing one returns 404
Tested for test env and still works
```
➜ aws-vault exec deploy -- node run-local/index.js --test make-recurring-card-payment-stripe --env test --headless
Running make-recurring-card-payment-stripe
Webhooks steps are disabled, pass --webhooks to enable them
Creating agreement for [stripe]
Created agreement [h4hvmff0fl8rcs1lfj1g9oc5vg]
Setting up a payment for [stripe] and agreement [h4hvmff0fl8rcs1lfj1g9oc5vg]
Created payment [v4kcadtmrjvrsu0o2afb9j1n09] for agreement [h4hvmff0fl8rcs1lfj1g9oc5vg]
Going to get page https://card.pymnt.uk/secure/2f46b830-6fc9-4f8e-8ca0-5e69f321e118
Finished setting up payment [v4kcadtmrjvrsu0o2afb9j1n09] for agreement …
```
=> PP-11029 Refactor Stripe rec card smoke test

.github/dependabot.yml
See [Github documentation for details](https://docs.github.com/en/code-security/dependabot/dependabot-security-updates/configuring-dependabot-security-updates). 
This config will:
- only open PRs for security updates for both `npm` and `github-actions` ecosystems.
=> PP-10970: Example of Dependabot config for security updates only

README.md, make-recurring-card-payment-worldpay/index.js, run-local/index.js, webpack.config.js
- Added new smoke test for Worldpay recurring card payments
<details>
<summary>aws-vault exec deploy -- node run-local/index.js --test make-recurring-card-payment-worldpay --env test --headless</summary>
```
Running make-recurring-card-payment-worldpay
Webhooks steps are disabled, pass --webhooks to enable them
Creating agreement for [worldpay]
Created agreement [2i1hvtug37jgj3of1v3lqes61o]
Setting up a payment for [worldpay] and agreement [2i1hvtug37jgj3of1v3lqes61o]
Created payment [vks8moc2na363t82ngu8m8s8g0] for agreement [2i1hvtug37jgj3of1v3lqes61o]
Going to get page https://card.pymnt.uk/secure/045a15ec-afa4-46cf-acb0-6951ba52b331
Finished setting up payment [vks8moc2na363t82ngu8m8s8g0] for agreement [2i1hvtug37jgj3of1v3lqes61o]
Payment [vks8moc2na363t82ngu8m8s8g0] status is success …
```
=> PP-10501 Add Worldpay recurring card payment smoke test

.github/workflows/run-tests.yml
I forgot to up the node version used to test and run. Instead of manually specifying it, this change will load it from the nvmrc
=> PP-11409: Update git workflow to use nvmrc version

README.md
The previous release was to a github workflow, which doesn't trigger the release workflow, but we need to do a new release on node18....so this is a no-op which will cause a release
=> PP-11409: No-op to trigger release workflow

make-card-payment-stripe-with-3ds2/index.js
- Updated Stripe card number to the one we specify in tech docs.
Works locally
`aws-vault exec deploy -- node run-local/index.js --test make-card-payment-stripe-with-3ds2 --env staging --headless`
=> BAU Update Stripe 3DS card number

make-card-payment-stripe-with-3ds2/index.js
The smoke test was failing with `Waiting for selector iframe.FullscreenFrame`. Upon inspection, the iframe we were interested is in the one with class "ThreeDS2-challenge", not "FullscreenFrame" - see screenshot attached to this PR. However, changing it to the correct name still didn't work. It is suspected that this is because there is an intermediary iframe between iframe-3ds and "ThreeDS2-challenge", so:
```
<iframe class="iframe-3ds">
<iframe name="__privateStripeFrame0504">
<iframe class="ThreeDS2-challenge">
</iframe>
</iframe>
</iframe>
```
We can't select the second iframe however because the name changes on each test run as it's not controlled by us, and there's no id or class attributes attached to it.
It seems the method presented in this commit works, so let's accept that and …
=> PP-12139: Fix Stripe 3DS smoke test

package-lock.json, package.json
This resolves a [security alert](https://github.com/alphagov/pay-smoke-tests/security/dependabot/15) on sub dependency xml2js. Not sure why Dependabot did not pick this up.
Note that this `aws-sdk` dependency is only used for local tests. For the deployed canaries, the AWS SDK is provided 'for free' in the canary runtime, and as such is up to date. 
This also means that we don't need a new canary deployment following this change.
I've tested the change by running some of the smoke tests locally according to the README instructions.
=> BAU: Update aws-sdk devDependency

helpers/smoke-test-helpers.js
- Sandbox smoke tests have been flaky and we are seeing the below errors for failed tests 
`ProtocolError: Protocol error (Page.captureScreenshot): Unable to capture screenshot` or `ProtocolError: Protocol error (Page.bringToFront): Not attached to an active page`
- The failed tests are missing the `Click confirm-starting` screenshot, so it is likely that there were page changes while the puppeteer was taking the screenshot.
- Sets the timeout before confirming the payment so there are no page changes during the screenshot.
=> PP-13405 Wait before confirming the payment

helpers/smoke-test-helpers.js
- Uses one version of `setTimeout` method for waiting. `wait()` method is broken (due to changes in https://github.com/alphagov/pay-smoke-tests/pull/238) as the params required are different for `setTimeout` function in `node:timers/promises`
=> PP-13405 Fix smoke tests

.github/workflows/post-merge.yml, .github/workflows/run-tests.yml
Github deprecated the version of `actions/cache` we were using. [We need to upgrade to v4.2.0](https://github.com/actions/cache/releases/tag/v4.2.0).
=> BAU: Upgrade deprecated actions/cache dependency to v4.2.0

run-local/index.js
Recent changes in connector has broken the smoke test. PP-14366 will fix that. However, we don't have any service taking recurring payments with Worldpay thus we can disable the test. This is so we don't have a `broken window` effect.
=> PP-14368 disable worldpay recurring card payment part 2
